### ISSUE TITLE
Python Bindings 

### ISSUE THREAD

**Issue by william-silversmith** [janelia-flyem/compressedseg#1]
Dr. Plaza,

I'm the author of [CloudVolume](https://github.com/seung-lab/cloud-volume), a Python client for reading and writing Neuroglancer Precomputed compatible files. I created a Cython extension based on your C++ code here. If you're interested, I'd be happy to add the Python bindings to this repo as well. Thank you for creating the decompression library!

You can find the code here: 

https://github.com/seung-lab/cloud-volume/blob/master/ext/third_party/compressed_segmentation/src/_compressed_segmentation.pyx

Will Silversmith

**Comment by stephenplaza** [comment]
Hi Will,

Thanks for creating a python extension!  I am happy to accept any pull request that adds your library. 

You might find https://github.com/janelia-flyem/diced interesting as it is a python interface that enables storage of large, versioned arrays in the cloud ... this works as a layer over DVID (which is essentially chunked volume data in a google bucket).
